### ISSUE TITLE
Linaria link is 404

### ISSUE THREAD

**Issue by e-jigsaw** [StateOfJS/StateOfCSS-2020#26]
https://linaria.dev/ :)

**Comment by SachaG** [comment]
It works for me?

**Comment by e-jigsaw** [comment]
<img width="463" alt=" 2020-12-03 21 24 54" src="https://user-images.githubusercontent.com/557961/101017869-033f6500-35ae-11eb-89bb-c04addd10860.png">

=>

<img width="989" alt=" 2020-12-03 21 25 28" src="https://user-images.githubusercontent.com/557961/101017914-13efdb00-35ae-11eb-9e71-b4cc8943c249.png">

**Comment by SachaG** [comment]
Oh sorry, I misunderstood and thought you were saying https://linaria.dev/ wasn't working. I'll fix it right away :)

**Comment by e-jigsaw** [comment]
🙌
