### ISSUE TITLE
Truncate nav link using ellipsis

### ISSUE THREAD

**Issue by lex111** [StateOfJS/StateOfCSS-2020#9]
When nav link is long, the sidebar gets horizontal scrolling, it is better to truncate the item with ellipsis instead.

![image](https://user-images.githubusercontent.com/4408379/99903485-c9c94880-2cd5-11eb-9e83-cd3ac5a5813b.png)

Something like this:

![image](https://user-images.githubusercontent.com/4408379/99903609-74da0200-2cd6-11eb-9b6a-d29fbd22b4ee.png)

cc @SachaG

**Comment by SachaG** [comment]
This literally took me 40 minutes to figure out… I hate CSS sometimes!
